-- Generated by scripts/gen-schema.mjs — do not edit by hand.
-- The full schema in one apply, for a fresh install. Existing databases
-- upgrade through the numbered migrations instead; this file is never
-- applied as a migration. Regenerate after adding a migration:
--   node scripts/gen-schema.mjs

CREATE TABLE grants (
  id            TEXT PRIMARY KEY,       -- random, not autoincrement: doesn't leak counts
  token_hash    TEXT NOT NULL UNIQUE,   -- SHA-256, base64url
  name          TEXT,                   -- admin-side label: "Bob Smith (donor)"
  note          TEXT,                   -- freeform: why this exists
  subject_json  TEXT,                   -- optional pre-loaded identity: {first,last,email,avatar}
  email         TEXT,                   -- if set: magic-link semantics (bind on redeem)
  scopes        TEXT NOT NULL,          -- space-separated
  max_redeems   INTEGER,                -- NULL = unlimited; counts sessions minted, not requests
  redeems       INTEGER NOT NULL DEFAULT 0,
  expires_at    INTEGER,                -- NULL = never
  session_ttl   INTEGER,                -- seconds; NULL = inherit app default
  created_at    INTEGER NOT NULL,
  created_by    TEXT NOT NULL,
  revoked_at    INTEGER,
  first_used_at INTEGER,
  last_used_at  INTEGER
, disabled_at INTEGER, expiry_ends_sessions INTEGER NOT NULL DEFAULT 1, sessions_invalid_before INTEGER);

CREATE INDEX grants_created_at ON grants (created_at DESC);

CREATE TABLE access_log (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  ts          INTEGER NOT NULL,
  event       TEXT NOT NULL,   -- redeem | deny | revoke | request | view | signin | signout
  grant_id    TEXT,
  session_sub TEXT,            -- `e:<email>` | `g:<id>`
  path        TEXT,
  status      INTEGER,
  ip_hash     TEXT,
  ua          TEXT,
  country     TEXT,
  referer     TEXT,
  reason      TEXT,            -- deny detail: bad-token | revoked | expired | exhausted | not-allowed
  bucket      INTEGER          -- floor(ts/3600) for `view` rows; NULL otherwise
);

CREATE INDEX access_log_ts ON access_log (ts DESC);

CREATE INDEX access_log_grant ON access_log (grant_id, ts DESC);

CREATE TABLE access_requests (
  id         TEXT PRIMARY KEY,
  email      TEXT NOT NULL,
  name       TEXT,
  note       TEXT,
  created_at INTEGER NOT NULL,
  status     TEXT NOT NULL,   -- pending | approved | denied | auto
  decided_at INTEGER,
  decided_by TEXT,
  grant_id   TEXT,
  ip_hash    TEXT             -- HMAC, for rate-limiting; never a raw address
, subject_json TEXT);

CREATE INDEX access_requests_created_at ON access_requests (created_at DESC);

CREATE INDEX access_requests_status ON access_requests (status, created_at DESC);

CREATE INDEX access_requests_email ON access_requests (email, created_at DESC);

CREATE UNIQUE INDEX access_requests_one_pending ON access_requests (email) WHERE status = 'pending';

CREATE TABLE access_log_daily (
  day      INTEGER NOT NULL,   -- floor(ts / 86400)
  event    TEXT NOT NULL,
  grant_id TEXT,
  path     TEXT,
  country  TEXT,
  events   INTEGER NOT NULL,   -- rows collapsed into this bucket
  clients  INTEGER NOT NULL,   -- distinct ip_hash values within it
  PRIMARY KEY (day, event, grant_id, path, country)
);

CREATE INDEX access_log_daily_day ON access_log_daily (day DESC);

CREATE INDEX access_log_daily_grant ON access_log_daily (grant_id, day DESC);

CREATE UNIQUE INDEX access_log_dedupe ON access_log (event, session_sub, path, bucket) WHERE bucket IS NOT NULL;

CREATE INDEX grants_disabled_at ON grants (disabled_at);

CREATE TABLE profiles (
  email       TEXT PRIMARY KEY,
  avatar      TEXT,
  -- Provenance for re-resolve/debug: 'upload' | 'url' | 'github' | 'gravatar'.
  avatar_src  TEXT,
  updated_at  INTEGER NOT NULL
, name TEXT);

CREATE TABLE pending_auth (
  id          TEXT PRIMARY KEY,
  email       TEXT NOT NULL,
  token_hash  TEXT NOT NULL,
  code_hash   TEXT NOT NULL,
  created_at  INTEGER NOT NULL,
  expires_at  INTEGER NOT NULL,
  consumed_at INTEGER,
  attempts    INTEGER NOT NULL DEFAULT 0
, ip_hash TEXT);

CREATE UNIQUE INDEX pending_auth_token ON pending_auth (token_hash);

CREATE INDEX pending_auth_email ON pending_auth (email, created_at);

CREATE INDEX pending_auth_ip ON pending_auth (ip_hash, created_at);

CREATE TABLE allowed_emails (
  email      TEXT PRIMARY KEY,       -- lowercased on write; the policy lowercases its lookup
  scopes     TEXT NOT NULL,          -- space-separated, same codec as grants.scopes
  source     TEXT NOT NULL DEFAULT 'manual',  -- provenance: 'manual' | 'sync:<group>'; a sync replaces only its own source
  note       TEXT,
  added_by   TEXT,                   -- the admin (or sync job) that wrote the row
  updated_at INTEGER NOT NULL
);

CREATE INDEX allowed_emails_source ON allowed_emails (source);
