#!/usr/bin/env node
/**
 * Regenerate `schema.sql` (package root) — the full current schema in one file, for
 * a fresh consumer who wants to stand up the tables in a single apply rather
 * than replaying every numbered migration.
 *
 * It is a *derived* artifact: this script applies the numbered migrations
 * (`NNNN_*.sql`) to an in-memory database in order and dumps the resulting
 * schema. `test/schema.test.ts` asserts the checked-in file still matches, so it
 * cannot silently drift — after adding a migration, run `node scripts/gen-schema.mjs`.
 *
 * The numbered migrations remain the source of truth and the upgrade path for an
 * existing database (a delta a live DB steps through); `schema.sql` is only the
 * greenfield shortcut and is never itself applied as a migration.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { DatabaseSync } from 'node:sqlite'

const migrationsDir = fileURLToPath(new URL('../migrations/', import.meta.url))

/** Only `NNNN_*.sql` are migrations; `schema.sql` (this output) is excluded. */
export const MIGRATION_RE = /^\d{4}_.*\.sql$/

/** Ordered list of migration filenames. */
export const migrationFiles = () => readdirSync(migrationsDir).filter(f => MIGRATION_RE.test(f)).sort()

/**
 * Apply every migration to a fresh in-memory DB and return the canonical schema
 * as SQLite stores it (each object's `CREATE …` text, ordered by creation), so
 * the same dump results whether a table was built by one `CREATE` or a `CREATE`
 * plus later `ALTER`s.
 */
export function dumpSchema() {
  const db = new DatabaseSync(':memory:')
  for (const name of migrationFiles()) db.exec(readFileSync(migrationsDir + name, 'utf8'))
  const rows = db
    .prepare(`SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY rowid`)
    .all()
  db.close()
  return rows.map(r => `${r.sql};`).join('\n\n')
}

const HEADER = [
  '-- Generated by scripts/gen-schema.mjs — do not edit by hand.',
  '-- The full schema in one apply, for a fresh install. Existing databases',
  '-- upgrade through the numbered migrations instead; this file is never',
  '-- applied as a migration. Regenerate after adding a migration:',
  '--   node scripts/gen-schema.mjs',
  '',
  '',
].join('\n')

function main() {
  // Deliberately *outside* `migrations/`: `wrangler d1 migrations apply` sweeps
  // every `.sql` in its dir, so a one-file dump in there re-creates `grants`
  // after the numbered files and dies.
  writeFileSync(new URL('../schema.sql', import.meta.url), HEADER + dumpSchema() + '\n')
  process.stderr.write(`wrote schema.sql (${migrationFiles().length} migrations)\n`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main()
